import Image from "next/image";
import { Card, CardContent } from "@/components/ui/card";
import { Check, X } from "lucide-react";

export default function PpaSection() {
	return (
		<section id="ppa" className="py-16">
			<div className="container">
				<div className="flex flex-col gap-8">
					<div className="text-center space-y-4">
						<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
							A Power Purchase Agreement (PPA) locks in your
							electricity price.
						</h2>
						<p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl">
							With a PPA, you pay for the power generated by solar
							panels installed on your property at a fixed,
							predictable rate—typically lower than utility rates.
						</p>
					</div>

					<Card className="overflow-hidden">
						<CardContent className="p-0">
							<div className="grid md:grid-cols-2">
								<div className="bg-muted p-6 md:p-8">
									<div className="flex flex-col gap-4">
										<div className="flex items-center gap-2">
											<div className="rounded-full bg-destructive/10 p-2">
												<X className="h-5 w-5 text-destructive" />
											</div>
											<h3 className="text-xl font-bold">
												Traditional Utility
											</h3>
										</div>
										<ul className="space-y-3">
											<li className="flex items-start gap-2">
												<X className="h-5 w-5 min-w-5 mt-0.5 text-destructive" />
												<span>
													Unpredictable rate increases
												</span>
											</li>
											<li className="flex items-start gap-2">
												<X className="h-5 w-5 min-w-5 mt-0.5 text-destructive" />
												<span>
													No control over energy costs
												</span>
											</li>
											<li className="flex items-start gap-2">
												<X className="h-5 w-5 min-w-5 mt-0.5 text-destructive" />
												<span>
													Vulnerable to inflation and
													market fluctuations
												</span>
											</li>
											<li className="flex items-start gap-2">
												<X className="h-5 w-5 min-w-5 mt-0.5 text-destructive" />
												<span>
													Dependent on fossil fuels
												</span>
											</li>
											<li className="flex items-start gap-2">
												<X className="h-5 w-5 min-w-5 mt-0.5 text-destructive" />
												<span>
													No home value increase
												</span>
											</li>
										</ul>
									</div>
								</div>

								<div className="bg-primary/5 p-6 md:p-8">
									<div className="flex flex-col gap-4">
										<div className="flex items-center gap-2">
											<div className="rounded-full bg-primary/10 p-2">
												<Check className="h-5 w-5 text-primary" />
											</div>
											<h3 className="text-xl font-bold">
												Solar PPA
											</h3>
										</div>
										<ul className="space-y-3">
											<li className="flex items-start gap-2">
												<Check className="h-5 w-5 min-w-5 mt-0.5 text-primary" />
												<span>
													Fixed, predictable energy
													rates
												</span>
											</li>
											<li className="flex items-start gap-2">
												<Check className="h-5 w-5 min-w-5 mt-0.5 text-primary" />
												<span>
													No upfront installation
													costs
												</span>
											</li>
											<li className="flex items-start gap-2">
												<Check className="h-5 w-5 min-w-5 mt-0.5 text-primary" />
												<span>
													Maintenance and repairs
													included
												</span>
											</li>
											<li className="flex items-start gap-2">
												<Check className="h-5 w-5 min-w-5 mt-0.5 text-primary" />
												<span>
													Clean, renewable energy
													source
												</span>
											</li>
											<li className="flex items-start gap-2">
												<Check className="h-5 w-5 min-w-5 mt-0.5 text-primary" />
												<span>
													Potential to increase home
													value
												</span>
											</li>
										</ul>
									</div>
								</div>
							</div>
						</CardContent>
					</Card>

					<div className="mt-8 grid gap-8 md:grid-cols-2 md:gap-12">
						<div className="relative h-[300px] md:h-auto">
							<Image
								src="/ppa.webp"
								alt="Chart comparing utility bills vs PPA costs over time"
								fill
								className="object-contain"
							/>
						</div>
						<div className="space-y-4">
							<h3 className="text-2xl font-bold">
								How a PPA Works
							</h3>
							<ol className="space-y-4">
								<li className="flex gap-4">
									<div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground">
										1
									</div>
									<div className="space-y-1">
										<p className="font-medium">
											Solar Installation
										</p>
										<p className="text-sm text-muted-foreground">
											We install solar panels on your
											property at no upfront cost to you.
										</p>
									</div>
								</li>
								<li className="flex gap-4">
									<div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground">
										2
									</div>
									<div className="space-y-1">
										<p className="font-medium">
											Energy Production
										</p>
										<p className="text-sm text-muted-foreground">
											The solar system generates
											electricity for your home.
										</p>
									</div>
								</li>
								<li className="flex gap-4">
									<div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground">
										3
									</div>
									<div className="space-y-1">
										<p className="font-medium">
											Fixed Payments
										</p>
										<p className="text-sm text-muted-foreground">
											You pay only for the power produced
											at a fixed, lower-than-utility rate.
										</p>
									</div>
								</li>
								<li className="flex gap-4">
									<div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground">
										4
									</div>
									<div className="space-y-1">
										<p className="font-medium">
											Maintenance Included
										</p>
										<p className="text-sm text-muted-foreground">
											We handle all maintenance, repairs,
											and monitoring of the system.
										</p>
									</div>
								</li>
							</ol>
						</div>
					</div>
				</div>
			</div>
		</section>
	);
}
